import com.haxepunk.Sfx;

class Global
{
    public static var BACKGROUND_AUDIO = new Sfx("audio/storm.ogg");
    public static var BACKGROUND_SIREN = new Sfx("audio/siren.ogg");
    public static var SFX_WHOOSH = new Sfx("audio/whoosh2.ogg");

    public static var TOWN_NAMES = [
        "Des Moines",
        "Cedar Rapids",
        "Davenport",
        "Sioux City",
        "Iowa City",
        "Adel",
        "De Soto",
        "Waterloo",
        "Council Bluffs",
        "Ames",
        "Dubuque",
        "West Des Moines",
        "Ankeny",
        "Urbandale",
        "Cedar Falls",
        "Marion",
        "Bettendorf",
        "Mason City",
        "Marshalltown",
        "Clinton",
        "Burlington",
        "Fort Dodge",
        "Ottumwa",
        "Muscatine",
        "Coralville",
        "Johnston",
        "Clive",
        "Newton",
        "Indianola",
        "Altoona",
        "Waukee",
        "North Liberty",
        "Boone",
        "Oskaloosa",
        "Spencer",
        "Fort Madison",
        "Keokuk",
        "Storm Lake",
        "Pella",
        "Carroll",
        "Waverly",
        "Le Mars",
        "Fairfield",
        "Grinnell",
        "Norwalk",
        "Mount Pleasant"];

    public static var COUNTY_NAMES = [
        "Adair",
        "Adams",
        "Allamakee",
        "Appanoose",
        "Audubon",
        "Benton",
        "Black Hawk",
        "Boone",
        "Bremer",
        "Buchanan",
        "Buena Vista",
        "Butler",
        "Calhoun",
        "Carroll",
        "Cass",
        "Cedar",
        "Cerro Gordo",
        "Cherokee",
        "Chickasaw",
        "Clarke",
        "Clay",
        "Clayton",
        "Clinton",
        "Crawford",
        "Dallas",
        "Davis",
        "Decatur",
        "Delaware",
        "Des Moines",
        "Dickinson",
        "Dubuque",
        "Emmet",
        "Fayette",
        "Floyd",
        "Franklin",
        "Fremont",
        "Greene",
        "Grundy",
        "Guthrie",
        "Hamilton",
        "Hancock",
        "Hardin",
        "Harrison",
        "Henry",
        "Howard",
        "Humboldt",
        "Ida",
        "Iowa",
        "Jackson",
        "Jasper",
        "Jefferson",
        "Johnson",
        "Jones",
        "Keokuk",
        "Kossuth",
        "Lee",
        "Linn",
        "Louisa",
        "Lucas",
        "Lyon",
        "Madison",
        "Mahaska",
        "Marion",
        "Marshall",
        "Mills",
        "Mitchell",
        "Monona",
        "Monroe",
        "Montgomery",
        "Muscatine",
        "O'Brien",
        "Osceola",
        "Page",
        "Palo Alto",
        "Plymouth",
        "Pocahontas",
        "Polk",
        "Pottawattamie",
        "Poweshiek",
        "Ringgold",
        "Sac",
        "Scott",
        "Shelby",
        "Sioux",
        "Story",
        "Tama",
        "Taylor",
        "Union",
        "Van Buren",
        "Wapello",
        "Warren",
        "Washington",
        "Wayne",
        "Webster",
        "Winnebago",
        "Winneshiek",
        "Woodbury",
        "Worth",
        "Wright"];
}
